name: medsam
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - nvidia
  - conda-forge
  - defaults
  - https://mirrors.ustc.edu.cn/anaconda/pkgs/msys2/
  - https://mirrors.ustc.edu.cn/anaconda/pkgs/r/
  - https://mirrors.ustc.edu.cn/anaconda/pkgs/main/
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - aom=3.5.0=h27087fc_0
  - blas=1.0=mkl
  - brotli-python=1.1.0=py310hf71b8c6_2
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2024.8.30=hbcca054_0
  - cairo=1.16.0=h35add3b_1015
  - certifi=2024.8.30=pyhd8ed1ab_0
  - cffi=1.17.1=py310h8deb56e_0
  - charset-normalizer=3.4.0=pyhd8ed1ab_1
  - cpython=3.10.16=py310hd8ed1ab_1
  - cuda-cudart=11.8.89=0
  - cuda-cupti=11.8.87=0
  - cuda-libraries=11.8.0=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-runtime=11.8.0=0
  - cuda-version=12.6=3
  - dav1d=1.2.1=hd590300_0
  - ffmpeg=6.0.0=gpl_hdbbbd96_103
  - filelock=3.16.1=pyhd8ed1ab_1
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.12.1=h267a509_2
  - fribidi=1.0.10=h36c2ea0_0
  - gettext=0.22.5=he02047a_3
  - gettext-tools=0.22.5=he02047a_3
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.1.5=py310he8512ff_3
  - gnutls=3.7.9=hb077bed_0
  - graphite2=1.3.13=h59595ed_1003
  - h2=4.1.0=pyhd8ed1ab_1
  - harfbuzz=7.3.0=hdb3a94d_0
  - hpack=4.0.0=pyhd8ed1ab_1
  - hyperframe=6.0.1=pyhd8ed1ab_1
  - icu=72.1=hcb278e6_0
  - idna=3.10=pyhd8ed1ab_1
  - intel-openmp=2022.0.1=h06a4308_3633
  - jinja2=3.1.4=pyhd8ed1ab_1
  - jpeg=9e=h0b41bf4_3
  - lame=3.100=h166bdaf_1003
  - lcms2=2.15=hfd0df8a_0
  - ld_impl_linux-64=2.43=h712a8e2_2
  - lerc=4.0.0=h27087fc_0
  - libasprintf=0.22.5=he8f35ee_3
  - libasprintf-devel=0.22.5=he8f35ee_3
  - libass=0.17.1=hc9aadba_0
  - libblas=3.9.0=16_linux64_mkl
  - libcblas=3.9.0=16_linux64_mkl
  - libcublas=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufile=1.11.1.6=0
  - libcurand=10.3.7.77=0
  - libcusolver=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libdeflate=1.17=h0b41bf4_0
  - libdrm=2.4.124=hb9d3cd8_0
  - libexpat=2.6.4=h5888daf_0
  - libffi=3.4.2=h7f98852_5
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgettextpo=0.22.5=he02047a_3
  - libgettextpo-devel=0.22.5=he02047a_3
  - libglib=2.82.2=h2ff4ddf_0
  - libgomp=14.2.0=h77fa898_1
  - libiconv=1.17=hd590300_2
  - libidn2=2.3.7=hd590300_0
  - liblapack=3.9.0=16_linux64_mkl
  - liblzma=5.6.3=hb9d3cd8_1
  - liblzma-devel=5.6.3=hb9d3cd8_1
  - libnpp=11.8.0.86=0
  - libnsl=2.0.1=hd590300_0
  - libnvjpeg=11.9.0.86=0
  - libopus=1.3.1=h7f98852_1
  - libpciaccess=0.18=hd590300_0
  - libpng=1.6.44=hadc24fc_0
  - libsqlite=3.47.0=hadc24fc_1
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-ng=14.2.0=h4852527_1
  - libtasn1=4.19.0=h166bdaf_0
  - libtiff=4.5.0=h6adf6a1_2
  - libunistring=0.9.10=h7f98852_0
  - libuuid=2.38.1=h0b41bf4_0
  - libva=2.18.0=h0b41bf4_0
  - libvpx=1.13.1=h59595ed_0
  - libwebp-base=1.4.0=hd590300_0
  - libxcb=1.13=h7f98852_1004
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.11.5=h0d562d8_0
  - libzlib=1.3.1=hb9d3cd8_2
  - markupsafe=3.0.2=py310h89163eb_1
  - mkl=2022.1.0=hc2b9512_224
  - mpc=1.3.1=h24ddda3_1
  - mpfr=4.2.1=h90cbb55_3
  - mpmath=1.3.0=pyhd8ed1ab_1
  - ncurses=6.5=he02047a_1
  - nettle=3.9.1=h7ab15ed_0
  - networkx=3.4.2=pyh267e887_2
  - openh264=2.3.1=hcb278e6_2
  - openjpeg=2.5.0=hfec8fc6_2
  - openssl=3.4.0=hb9d3cd8_0
  - p11-kit=0.24.1=hc5aa10d_0
  - pcre2=10.44=hba22ea6_2
  - pillow=9.4.0=py310h023d228_1
  - pip=24.3.1=pyh8b19718_0
  - pixman=0.43.2=h59595ed_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pycparser=2.22=pyh29332c3_1
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.10.16=he725a3c_1_cpython
  - python_abi=3.10=5_cp310
  - pytorch-cuda=11.8=h7e8668a_6
  - pytorch-mutex=1.0=cuda
  - readline=8.2=h8228510_1
  - requests=2.32.3=pyhd8ed1ab_1
  - setuptools=75.6.0=pyhff2d567_1
  - svt-av1=1.6.0=h59595ed_0
  - tk=8.6.13=noxft_h4845f30_101
  - typing_extensions=4.12.2=pyha770c72_1
  - urllib3=2.2.3=pyhd8ed1ab_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xorg-fixesproto=5.0=hb9d3cd8_1003
  - xorg-kbproto=1.0.7=hb9d3cd8_1003
  - xorg-libice=1.1.1=hb9d3cd8_1
  - xorg-libsm=1.2.4=he73a12e_1
  - xorg-libx11=1.8.4=h0b41bf4_0
  - xorg-libxau=1.0.11=hb9d3cd8_1
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-renderproto=0.11.1=hb9d3cd8_1003
  - xorg-xextproto=7.3.0=hb9d3cd8_1004
  - xorg-xproto=7.0.31=hb9d3cd8_1008
  - xz=5.6.3=hbcc6ac9_1
  - xz-gpl-tools=5.6.3=hbcc6ac9_1
  - xz-tools=5.6.3=hb9d3cd8_1
  - zlib=1.3.1=hb9d3cd8_2
  - zstandard=0.23.0=py310ha39cb0e_1
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
      - annotated-types==0.7.0
      - anyio==4.7.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==3.0.0
      - async-lru==2.0.4
      - attrs==24.2.0
      - babel==2.16.0
      - beautifulsoup4==4.12.3
      - bleach==6.2.0
      - blis==1.1.0
      - catalogue==2.0.10
      - click==8.1.8
      - cloudpathlib==0.20.0
      - comm==0.2.2
      - confection==0.1.5
      - contourpy==1.3.1
      - cycler==0.12.1
      - cymem==2.0.10
      - debugpy==1.8.9
      - decorator==5.1.1
      - defusedxml==0.7.1
      - en-core-web-sm==3.8.0
      - exceptiongroup==1.2.2
      - executing==2.1.0
      - fastjsonschema==2.21.1
      - fonttools==4.55.2
      - fqdn==1.5.1
      - fsspec==2024.12.0
      - h11==0.14.0
      - httpcore==1.0.7
      - httpx==0.28.1
      - huggingface-hub==0.27.1
      - imageio==2.36.1
      - importlib-resources==6.4.5
      - ipykernel==6.29.5
      - ipympl==0.9.4
      - ipython==8.30.0
      - ipython-genutils==0.2.0
      - ipywidgets==8.1.5
      - isoduration==20.11.0
      - jedi==0.19.2
      - joblib==1.4.2
      - json5==0.10.0
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter==1.1.1
      - jupyter-client==8.6.3
      - jupyter-console==6.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.2
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.3.4
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.13
      - kiwisolver==1.4.7
      - langcodes==3.5.0
      - language-data==1.3.0
      - lazy-loader==0.4
      - lpips==0.1.4
      - marisa-trie==1.2.1
      - markdown-it-py==3.0.0
      - matplotlib==3.9.3
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mistune==3.0.2
      - monai==1.4.0
      - murmurhash==1.0.11
      - natsort==8.4.0
      - nbclient==0.10.1
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - nibabel==5.3.2
      - notebook==7.3.2
      - notebook-shim==0.2.4
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - opencv-python==4.10.0.84
      - overrides==7.7.0
      - packaging==24.2
      - pandas==2.3.0
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pexpect==4.9.0
      - platformdirs==4.3.6
      - preshed==3.0.9
      - prometheus-client==0.21.1
      - prompt-toolkit==3.0.48
      - protobuf==5.29.2
      - psutil==6.1.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pydantic==2.10.4
      - pydantic-core==2.27.2
      - pygments==2.18.0
      - pyparsing==3.2.0
      - python-dateutil==2.9.0.post0
      - python-json-logger==2.0.7
      - pytz==2025.2
      - pyyaml==6.0.2
      - pyzmq==26.2.0
      - referencing==0.35.1
      - regex==2024.11.6
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.9.4
      - rpds-py==0.22.3
      - safetensors==0.5.1
      - scikit-image==0.24.0
      - scikit-learn==1.5.2
      - scipy==1.14.1
      - send2trash==1.8.3
      - shellingham==1.5.4
      - simpleitk==2.4.0
      - six==1.17.0
      - smart-open==7.1.0
      - sniffio==1.3.1
      - soupsieve==2.6
      - spacy==3.8.3
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - srsly==2.5.0
      - stack-data==0.6.3
      - sympy==1.13.1
      - tensorboardx==2.6.2.2
      - terminado==0.18.1
      - thinc==8.3.3
      - threadpoolctl==3.5.0
      - tifffile==2024.9.20
      - timm==1.0.13
      - tinycss2==1.4.0
      - tokenizers==0.21.0
      - tomli==2.2.1
      - torch==2.5.1
      - torchaudio==2.5.1
      - torchvision==0.20.1
      - tornado==6.4.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.47.1
      - triton==3.1.0
      - typer==0.15.1
      - types-python-dateutil==2.9.0.20241206
      - tzdata==2025.2
      - uri-template==1.3.0
      - wasabi==1.1.3
      - wcwidth==0.2.13
      - weasel==0.4.1
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - widgetsnbextension==4.0.13
      - wrapt==1.17.0
      - yacs==0.1.8
prefix: /home/friedai/anaconda3/envs/medsam
